# Pre-commit configuration file
# For more information, refer to https://pre-commit.com

repos:
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
      - id: terraform_fmt
      #- id: terraform_tflint
      - id: terraform_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true
          - --tf-init-args=-upgrade
      - id: terraform_docs
        args:
          - '--args=--lockfile=false'
          - '--args=--config=.terraform-docs.yaml'
      # - id: terraform_trivy
      #   args:
      #     - --args=--format=json
      #     - --args=--skip-dirs="**/.terraform"
      # - id : terraform_checkov
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Security analysis to prevent sensitive data leakage
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
